<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer
{
    const METHOD_MAPPING = array (
    'pages.prefix' => 'get1',
    'admin.widgets' => 'get2',
    'subEntry1' => 'get3',
    'news.prefix' => 'get4',
    'admin.prefix' => 'get5',
    'App\\Admin\\AdminModule' => 'get6',
    'subEntry2' => 'get7',
    'subEntry3' => 'get8',
    'subEntry4' => 'get9',
    'App\\Admin\\Actions\\DashboardAction' => 'get10',
    'subEntry5' => 'get11',
    'subEntry6' => 'get12',
    'env' => 'get13',
    'database.host' => 'get14',
    'database.username' => 'get15',
    'database.password' => 'get16',
    'database.name' => 'get17',
    'views.path' => 'get18',
    'twig.extensions' => 'get19',
    'subEntry7' => 'get20',
    'subEntry8' => 'get21',
    'subEntry9' => 'get22',
    'subEntry10' => 'get23',
    'subEntry11' => 'get24',
    'subEntry12' => 'get25',
    'Framework\\Renderer\\RendererInterface' => 'get26',
    'Framework\\Session\\SessionInterface' => 'get27',
    'Framework\\Middleware\\CsrfMiddleware' => 'get28',
    'subEntry13' => 'get29',
    'Framework\\Router' => 'get30',
    'PDO' => 'get31',
    'App\\News\\NewsWidget' => 'get32',
    'subEntry14' => 'get33',
    'Utils\\RouterTwigExtension' => 'get34',
    'subEntry15' => 'get35',
    'Utils\\TwigPagerFantaExtension' => 'get36',
    'subEntry16' => 'get37',
    'Utils\\TwigTextExtension' => 'get38',
    'Utils\\TwigFlashExtension' => 'get39',
    'subEntry17' => 'get40',
    'Utils\\TwigFormExtension' => 'get41',
    'Utils\\CsrfTwigExtension' => 'get42',
    'subEntry18' => 'get43',
    'Framework\\Session\\FlashService' => 'get44',
    'subEntry19' => 'get45',
    );

    protected function get1()
    {
        return '/pages';
    }

    protected function get3()
    {
        return $this->delegateContainer->get('App\\News\\NewsWidget');
    }

    protected function get2()
    {
        return [
            0 => $this->get3(),
        ];
    }

    protected function get4()
    {
        return '/news';
    }

    protected function get5()
    {
        return '/admin';
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Framework\\Renderer\\RendererInterface');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('Framework\\Router');
    }

    protected function get9()
    {
        return $this->delegateContainer->get('admin.prefix');
    }

    protected function get6()
    {
        $object = new App\Admin\AdminModule($this->get7(), $this->get8(), $this->get9());
        return $object;
    }

    protected function get11()
    {
        return $this->delegateContainer->get('Framework\\Renderer\\RendererInterface');
    }

    protected function get12()
    {
        return $this->delegateContainer->get('admin.widgets');
    }

    protected function get10()
    {
        $object = new App\Admin\Actions\DashboardAction($this->get11(), $this->get12());
        return $object;
    }

    protected function get13()
    {
                $value = $_ENV['ENV'] ?? $_SERVER['ENV'] ?? getenv('ENV');
        if (false !== $value) {
            return $value;
        }
        if (!true) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'ENV' has not been defined");
        }
        return 'production';
    }

    protected function get14()
    {
        return 'localhost';
    }

    protected function get15()
    {
        return 'root';
    }

    protected function get16()
    {
        return '';
    }

    protected function get17()
    {
        return 'simplefm2';
    }

    protected function get18()
    {
        return 'C:\\laragon\\www\\v2-ut-perso/app/views';
    }

    protected function get20()
    {
        return $this->delegateContainer->get('Utils\\RouterTwigExtension');
    }

    protected function get21()
    {
        return $this->delegateContainer->get('Utils\\TwigPagerFantaExtension');
    }

    protected function get22()
    {
        return $this->delegateContainer->get('Utils\\TwigTextExtension');
    }

    protected function get23()
    {
        return $this->delegateContainer->get('Utils\\TwigFlashExtension');
    }

    protected function get24()
    {
        return $this->delegateContainer->get('Utils\\TwigFormExtension');
    }

    protected function get25()
    {
        return $this->delegateContainer->get('Utils\\CsrfTwigExtension');
    }

    protected function get19()
    {
        return [
            0 => $this->get20(),
            1 => $this->get21(),
            2 => $this->get22(),
            3 => $this->get23(),
            4 => $this->get24(),
            5 => $this->get25(),
        ];
    }

    protected function get26()
    {
        return $this->resolveFactory('Framework\\Renderer\\TwigRendererFactory', 'Framework\\Renderer\\RendererInterface');
    }

    protected function get27()
    {
        $object = new Framework\Session\PHPSession();
        return $object;
    }

    protected function get29()
    {
        return $this->delegateContainer->get('Framework\\Session\\SessionInterface');
    }

    protected function get28()
    {
        $object = new Framework\Middleware\CsrfMiddleware($this->get29(), 50, '_csrf', 'csrf');
        return $object;
    }

    protected function get30()
    {
        $object = new Framework\Router();
        return $object;
    }

    protected function get31()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            return new \PDO(
                'mysql:host=' . $c->get('database.host') . ';dbname=' . $c->get('database.name'),
                $c->get('database.username'),
                $c->get('database.password'),
                [
                     \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_OBJ,
                     \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
                 ]
            );
        }, 'PDO');
    }

    protected function get33()
    {
        return $this->delegateContainer->get('Framework\\Renderer\\RendererInterface');
    }

    protected function get32()
    {
        $object = new App\News\NewsWidget($this->get33());
        return $object;
    }

    protected function get35()
    {
        return $this->delegateContainer->get('Framework\\Router');
    }

    protected function get34()
    {
        $object = new Utils\RouterTwigExtension($this->get35());
        return $object;
    }

    protected function get37()
    {
        return $this->delegateContainer->get('Framework\\Router');
    }

    protected function get36()
    {
        $object = new Utils\TwigPagerFantaExtension($this->get37());
        return $object;
    }

    protected function get38()
    {
        $object = new Utils\TwigTextExtension();
        return $object;
    }

    protected function get40()
    {
        return $this->delegateContainer->get('Framework\\Session\\FlashService');
    }

    protected function get39()
    {
        $object = new Utils\TwigFlashExtension($this->get40());
        return $object;
    }

    protected function get41()
    {
        $object = new Utils\TwigFormExtension();
        return $object;
    }

    protected function get43()
    {
        return $this->delegateContainer->get('Framework\\Middleware\\CsrfMiddleware');
    }

    protected function get42()
    {
        $object = new Utils\CsrfTwigExtension($this->get43());
        return $object;
    }

    protected function get45()
    {
        return $this->delegateContainer->get('Framework\\Session\\SessionInterface');
    }

    protected function get44()
    {
        $object = new Framework\Session\FlashService($this->get45());
        return $object;
    }
}
